name: isaac-sim-lrp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - assimp=5.2.5=hf40c2ba_0
  - blas=2.3=openblas
  - boost=1.78.0=py37h48bf904_0
  - boost-cpp=1.78.0=h75c5d50_1
  - brotlipy=0.7.0=py37h540881e_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py37h43b0acd_1
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - console_bridge=1.0.2=h924138e_1
  - cryptography=38.0.2=py37h5994e8b_1
  - cuda-cccl=12.0.140=0
  - cuda-command-line-tools=12.0.1=0
  - cuda-compiler=12.0.1=0
  - cuda-cudart=12.0.146=0
  - cuda-cudart-dev=12.0.146=0
  - cuda-cudart-static=12.0.146=0
  - cuda-cuobjdump=12.0.140=0
  - cuda-cupti=12.0.146=0
  - cuda-cupti-static=12.0.146=0
  - cuda-cuxxfilt=12.0.140=0
  - cuda-documentation=12.0.140=0
  - cuda-driver-dev=12.0.146=0
  - cuda-gdb=12.0.140=0
  - cuda-libraries=12.0.1=0
  - cuda-libraries-dev=12.0.1=0
  - cuda-libraries-static=12.0.1=0
  - cuda-nsight=12.0.140=0
  - cuda-nsight-compute=12.0.1=0
  - cuda-nvcc=12.0.140=0
  - cuda-nvdisasm=12.0.140=0
  - cuda-nvml-dev=12.0.140=0
  - cuda-nvprof=12.0.146=0
  - cuda-nvprune=12.0.140=0
  - cuda-nvrtc=12.0.140=0
  - cuda-nvrtc-dev=12.0.140=0
  - cuda-nvrtc-static=12.0.140=0
  - cuda-nvtx=12.0.140=0
  - cuda-nvvp=12.0.146=0
  - cuda-opencl=12.0.140=0
  - cuda-opencl-dev=12.0.140=0
  - cuda-profiler-api=12.0.140=0
  - cuda-sanitizer-api=12.0.140=0
  - cuda-toolkit=11.7.1=0
  - cuda-tools=12.0.1=0
  - cuda-visual-tools=12.0.1=0
  - cudatoolkit=11.3.1=h9edb442_11
  - cudnn=8.4.1.50=hed8a83a_0
  - eigen=3.4.0=h4bd325d_0
  - eigenpy=2.7.14=py37h68ba05b_1
  - flit-core=3.8.0=pyhd8ed1ab_0
  - freetype=2.12.1=hca18f0e_1
  - future=0.18.2=py37h89c1867_5
  - gds-tools=1.5.1.14=0
  - giflib=5.2.1=h36c2ea0_2
  - hpp-fcl=2.1.4=py37hc995cdb_1
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h0b41bf4_3
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=3_openblas
  - libcblas=3.9.0=3_openblas
  - libcublas=12.0.2.224=0
  - libcublas-dev=12.0.2.224=0
  - libcublas-static=12.0.2.224=0
  - libcufft=11.0.1.95=0
  - libcufft-dev=11.0.1.95=0
  - libcufft-static=11.0.1.95=0
  - libcufile=1.5.1.14=0
  - libcufile-dev=1.5.1.14=0
  - libcufile-static=1.5.1.14=0
  - libcurand=10.3.1.124=0
  - libcurand-dev=10.3.1.124=0
  - libcurand-static=10.3.1.124=0
  - libcusolver=11.4.3.1=0
  - libcusolver-dev=11.4.3.1=0
  - libcusolver-static=11.4.3.1=0
  - libcusparse=12.0.1.140=0
  - libcusparse-dev=12.0.1.140=0
  - libcusparse-static=12.0.1.140=0
  - libdeflate=1.14=h166bdaf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=12.2.0=h65d4601_19
  - libhwloc=2.8.0=h32351e8_1
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=3_openblas
  - liblapacke=3.9.0=3_openblas
  - libnpp=12.0.1.104=0
  - libnpp-dev=12.0.1.104=0
  - libnpp-static=12.0.1.104=0
  - libnsl=2.0.0=h7f98852_0
  - libnvjitlink=12.0.140=0
  - libnvjitlink-dev=12.0.140=0
  - libnvjpeg=12.0.1.102=0
  - libnvjpeg-dev=12.0.1.102=0
  - libnvjpeg-static=12.0.1.102=0
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.21.12=h3eb15da_0
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.4.0=h82bc61c_5
  - libwebp=1.2.4=h522a892_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=hcb278e6_0
  - magma=2.5.4=hc72dce7_4
  - mkl=2022.2.1=h84fe81f_16997
  - mkl-service=2.4.0=py37h94185c7_0
  - mkl_fft=1.3.1=py37h90e98c2_3
  - mkl_random=1.2.2=py37h693438c_1
  - nccl=2.14.3.1=h0800d71_0
  - ncurses=6.3=h27087fc_1
  - ninja=1.11.0=h924138e_0
  - ninja-base=1.10.2=hd09550d_5
  - nsight-compute=2022.4.1.6=0
  - numpy=1.20.3=py37h038b26d_0
  - numpy-base=1.18.5=py37h2f8d375_0
  - octomap=1.9.8=h924138e_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.0.8=h0b41bf4_0
  - pillow=9.2.0=py37h850a105_2
  - pinocchio=2.6.10=py37hd988563_1
  - pip=23.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.12=hf930737_100_cpython
  - python_abi=3.7=3_cp37m
  - pytorch=1.12.1=cuda112py37h6a44366_201
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0=py37h540881e_4
  - qhull=2020.2=h4bd325d_2
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.2=pyhd8ed1ab_0
  - setuptools=67.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - sqlite=3.40.0=h4ff8645_0
  - tbb=2021.7.0=h924138e_1
  - tinyxml=2.6.2=h4bd325d_2
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.12.1=py37_cu113
  - torchvision=0.13.0=cuda112py37h67e586c_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - urdfdom=3.1.0=h068d047_1
  - urdfdom_headers=1.1.0=h924138e_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
  - pip:
      - absl-py==1.4.0
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.8
      - appdirs==1.4.4
      - attrs==22.2.0
      - cachetools==5.3.0
      - cloudpickle==2.2.1
      - cycler==0.11.0
      - cython==0.29.33
      - decorator==4.4.2
      - distlib==0.3.6
      - docker-pycreds==0.4.0
      - exceptiongroup==1.1.0
      - filelock==3.9.0
      - fonttools==4.38.0
      - frozenlist==1.3.3
      - gitdb==4.0.10
      - gitpython==3.1.30
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.1
      - gym==0.21.0
      - hydra-core==1.1.1
      - imageio==2.25.1
      - imageio-ffmpeg==0.4.8
      - importlib-metadata==4.13.0
      - importlib-resources==5.10.2
      - iniconfig==2.0.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - markdown==3.4.1
      - markupsafe==2.1.2
      - matplotlib==3.5.3
      - moviepy==1.0.3
      - msgpack==1.0.4
      - mushroom-rl==1.7.1
      - numpy-ml==0.1.2
      - oauthlib==3.2.2
      - omegaconf==2.1.1
      - opencv-python==4.7.0.68
      - packaging==23.0
      - pandas==1.3.5
      - platformdirs==3.0.0
      - pluggy==1.0.0
      - proglog==0.1.10
      - protobuf==3.20.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygame==2.1.2
      - pyparsing==3.0.9
      - pytest==7.2.1
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - ray==2.2.0
      - redis==3.5.3
      - requests-oauthlib==1.3.1
      - rl-games==1.5.2
      - rsa==4.9
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - setproctitle==1.3.2
      - smmap==5.0.0
      - stable-baselines3==1.6.2
      - tensorboard==2.11.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6
      - threadpoolctl==3.1.0
      - tomli==2.0.1
      - tqdm==4.64.1
      - virtualenv==20.19.0
      - wandb==0.13.10
      - werkzeug==2.2.2
      - zipp==3.13.0
prefix: /home/sjauhri/miniconda3/envs/isaac-sim-lrp
